from setuptools import setup, find_packages
setup(
    name='astronova-core',
    version='1.0.0',
    packages=find_packages(),
    install_requires=[
        'fastapi>=0.115.0',
        'pydantic>=2.9.0',
        'sqlalchemy>=2.0.0',
        'asyncpg>=0.30.0',
        'redis>=5.2.0',
        'confluent-kafka>=2.6.0',
        'prometheus-client>=0.21.0',
        'python-jose[cryptography]>=3.3.0',
        'passlib[bcrypt]>=1.7.4',
        'pandas>=2.2.0',
        'numpy>=2.0.0',
        'structlog>=24.0.0',
    ]
)
